export let EXCHANGE_DATA = [
    { id: '1', value: 'USA', width: '20%' },
    { id: '2', value: '美金', width: '7%' },
    { id: '3', value: 'C1', width: '20%' },
    { id: '4', value: 'D1', width: '30%' },
    { id: '5', value: 'Japan', width: '20%' },
    { id: '6', value: '日幣', width: '7%' },
    { id: '7', value: 'C2', width: '20%' },
    { id: '8', value: 'D2', width: '30%' },
    { id: '9', value: 'China', width: '20%' },
    { id: '10', value: '人民幣', width: '7%' },
    { id: '11', value: 'C3', width: '20%' },
    { id: '12', value: 'D3', width: '30%' },
    { id: '13', value: 'Europe', width: '20%' },
    { id: '14', value: '歐元', width: '7%' },
    { id: '15', value: 'C4', width: '20%' },
    { id: '16', value: 'D4', width: '30%' },
    { id: '17', value: 'HongKong', width: '20%' },
    { id: '18', value: '港幣', width: '7%' },
    { id: '19', value: 'C4', width: '20%' },
    { id: '20', value: 'D4', width: '30%' },
];